POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNjc5MDYwNjI0LCJleHAiOjE2NzkwNjQyMjR9.ywbZpcgFJI3qKSBsNlCT_o5XPZPqDg2dSPxdfaY0UlM

{
    "title": "Practice the guitar",
    "description": "And play like a rockstar" 
}