POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NzY3MzE2MzAsImV4cCI6MTY3NjczNTIzMH0.iBFWcIrzoX55CDNHtjm5rU85seo0JqRMFQh9l_BCqfQ

{
    "title": "Practice the guitar",
    "description": "And play like a rockstar" 
}