GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NzY3MzA0MjIsImV4cCI6MTY3NjczNDAyMn0.ABoEkvWyEeplnjwjS00Ax918nAOtxdua4Mor42vXp3U

###

GET http://localhost:3000/tasks?status=IN_PROGRESS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NzY3MjM5MjcsImV4cCI6MTY3NjcyNzUyN30.3tI4vV8MFFG9TerI3FywMt1aQr3zjRffq2K4faEEjl0

###

GET http://localhost:3000/tasks?q=DISHES
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NzY3MjM5MjcsImV4cCI6MTY3NjcyNzUyN30.3tI4vV8MFFG9TerI3FywMt1aQr3zjRffq2K4faEEjl0

###

GET http://localhost:3000/tasks?q=DISHES&status=IN_PROGRESS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NzY3MjM5MjcsImV4cCI6MTY3NjcyNzUyN30.3tI4vV8MFFG9TerI3FywMt1aQr3zjRffq2K4faEEjl0
