GET http://localhost:3000/tasks/a527cd38-f7c2-44a6-9907-da78b02724df
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NzY3MjY5NjcsImV4cCI6MTY3NjczMDU2N30.gsDzKmOc1Mv1su53u1Fac7Fb4XQv-lqoPXQOTxwmn4M