GET http://localhost:3000/tasks/cdce5f86-e831-4264-b540-8251ad653da2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE2NzY3Mzk2NjEsImV4cCI6MTY3Njc0MzI2MX0.8NGaS0iO_XyVfU9Y5blX6rcSCTAqUqdGT7cnBF-z110